#!/bin/bash

mlton -verbose 1 -default-type intinf -output Kruskal Kruskal.mlb
mlton -verbose 1 -default-type intinf -output Kruskal_tree Kruskal_tree.mlb

# mlton -verbose 1 -profile time -default-type intinf -output Fifo Fifo.mlb

